language: java

jdk:
  - oraclejdk8

script:
  - mvn clean compile test
  - mvn package -Dcheckstyle.skip=true -DskipTests=true -Dmaven.javadoc.skip=true 
  - release/protoc_install.sh
  - release/install.sh
