language: java

jdk:
  - oraclejdk8

sudo: false
dist: "trusty"
addons:
  apt:
    packages:
      - "python3-pip"

sudo: required
  - sudo pip3 install protobuf
  - sudo pip3 install tensorflow

script:
  - mvn clean compile -Dcheckstyle.skip=true
  - mvn package -Dcheckstyle.skip=true -DskipTests=true -Dmaven.javadoc.skip=true 
  - release/install.sh
