language: java

jdk:
  - oraclejdk8

sudo: false
dist: "trusty"
addons:
  apt:
    packages:
      - "python3-pip"

before_install:
  - pip3 install protobuf
  - pip3 install tensorflow

script:
  - mvn clean compile test
  - mvn package -Dcheckstyle.skip=true -DskipTests=true -Dmaven.javadoc.skip=true 
  - release/install.sh
