language: java

jdk:
  - oraclejdk8

sudo: false
dist: "trusty"
addons:
  apt:
    packages:
      - "python3-pip"

install:
  - sudo pip3 install protobuf tensorflow

script:
  - mvn clean compile test
  - mvn package -Dcheckstyle.skip=true -DskipTests=true -Dmaven.javadoc.skip=true 
  - release/install.sh
